---
- hosts: db
  vars: 
    item: 
      - python3-mysql
      - mysql-server

  name: mysql configurasyonu
  tasks:
    - name: mysql ve phyton kur
      yum:
        name: "{{ item }}" 
        state: present
              
    - name: sql'i başlat
      service:
        name: mariadb
        state: started
        enabled: true
