---
- hosts: db
  name: mysql configurasyonu
  tasks:
    - name: mysql ve phyton kur
      yum:
        name: "{{ item }}" 
        update_cache: yes
        cache_valid_time: 3600
        state: present
        with_items:
          - python3-mysqldb
          - mysql-server
    
    - name: sql'i başlat
      service:
        name: mysql
        state: started
        enabled: true
